electricity_price_eur_per_kwh: 0.2902
timezone: Europe/Berlin

mqtt:
  host: localhost
  port: 1883
  topic_prefix: shellies

plugs:
  - id: bkw
    name: Balkonkraftwerk
    role: producer

  - id: fridge
    name: Kühlschrank
    role: consumer
